import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const museoSans = localFont({
  src: [
    {
      path: "../assets/fonts/fonnts.com-Museo_Sans_Rounded_100.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../assets/fonts/fonnts.com-Museo_Sans_Rounded_300.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/fonnts.com-Museo_Sans_Rounded_500.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/fonnts.com-Museo_Sans_Rounded_700.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/fonnts.com-Museo_Sans_Rounded_900.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-museo-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${museoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
